---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - bin/**/*
    - gemfiles/**/*
    - vendor/**/*
    - Gemfile
    - Rakefile
    - "*.gemspec"
    - config.ru

Naming/ClassAndModuleCamelCase:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
