# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ofx}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2009-11-13}
  s.description = %q{A simple OFX (Open Financial Exchange) parser built on top of Nokogiri. Currently supports OFX 1.0.2.
}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/ofx.rb",
     "lib/ofx/account.rb",
     "lib/ofx/balance.rb",
     "lib/ofx/foundation.rb",
     "lib/ofx/parser.rb",
     "lib/ofx/parser/ofx102.rb",
     "lib/ofx/transaction.rb",
     "lib/ofx/version.rb",
     "ofx.gemspec",
     "spec/fixtures/sample.ofx",
     "spec/ofx/account_spec.rb",
     "spec/ofx/ofx102_spec.rb",
     "spec/ofx/ofx_parser_spec.rb",
     "spec/ofx/ofx_spec.rb",
     "spec/ofx/transaction_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fnando/ofx}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple OFX (Open Financial Exchange) parser built on top of Nokogiri. Currently supports OFX 1.0.2.}
  s.test_files = [
    "spec/ofx/account_spec.rb",
     "spec/ofx/ofx102_spec.rb",
     "spec/ofx/ofx_parser_spec.rb",
     "spec/ofx/ofx_spec.rb",
     "spec/ofx/transaction_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end
