# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{recurrence}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-09-14}
  s.description = %q{}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "History.txt",
     "License.txt",
     "README.markdown",
     "Rakefile",
     "init.rb",
     "lib/recurrence.rb",
     "lib/recurrence/event.rb",
     "lib/recurrence/event/base.rb",
     "lib/recurrence/event/daily.rb",
     "lib/recurrence/event/monthly.rb",
     "lib/recurrence/event/weekly.rb",
     "lib/recurrence/event/yearly.rb",
     "lib/recurrence/namespace.rb",
     "lib/recurrence/version.rb",
     "recurrence.gemspec",
     "spec/recurrence_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fnando/recurrence}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple library to handle recurring events}
  s.test_files = [
    "spec/recurrence_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

